/* ============================================================
   icons.js  -  8-bit pixel icons that stand in for emoji.

   Each icon is a 12x12 pixel map using the letters in PALETTE
   ('.' is see-through). A black outline is added automatically
   around the filled pixels, so a map only needs the colours.

   initPixelIcons() watches the page and swaps every emoji that has
   an icon here for the pixel version, wherever it shows up (cards,
   windows, toasts...), so the data files can keep using emoji.
   Emoji without an icon yet are left alone.
   ============================================================ */

const PALETTE = {
  k: '#181010', w: '#f8f8f8', l: '#c8c8d0', g: '#888890', d: '#505058',
  r: '#e83828', R: '#a01818', o: '#f89030', y: '#f8d030', Y: '#c88810',
  G: '#58d048', E: '#208030', b: '#3878f0', B: '#1848a0', c: '#98d8f8',
  p: '#b058d8', P: '#6a2890', n: '#b06830', N: '#683818', m: '#f878b0',
  s: '#f8b888', S: '#c87848', e: '#a0e878', u: '#f8a8c8',
};

const ICONS = {
  '⚔️': [
    '............',
    '.w........w.',
    '.lw......wl.',
    '..lw....wl..',
    '...lw..wl...',
    '....lwwl....',
    '....wllw....',
    '...yl..ly...',
    '..Nyy..yyN..',
    '.NN......NN.',
    '.N........N.',
    '............',
  ],
  '💀': [
    '............',
    '...wwwwww...',
    '..wwwwwwww..',
    '.wwwwwwwwwl.',
    '.wkkwwwkkwl.',
    '.wkkwwwkkwl.',
    '.wwwwkwwwwl.',
    '..wwwwwwwl..',
    '...wkwkwk...',
    '...wwwwww...',
    '............',
    '............',
  ],
  '🏥': [
    '............',
    '....rrrr....',
    '..rrrrrrrr..',
    '.RRRRRRRRRR.',
    '.wwwwwwwwww.',
    '.wccwwwwccw.',
    '.wccwrrwccw.',
    '.wwwwrrwwww.',
    '.wwwwkkwwww.',
    '.llllkkllll.',
    '............',
    '............',
  ],
  '🎁': [
    '............',
    '..yy....yy..',
    '...yy..yy...',
    '.rrrryyrrrr.',
    '.RRRRyyRRRR.',
    '............',
    '..rrryyrrr..',
    '..rrryyrrr..',
    '..rrryyrrr..',
    '..RRRyyRRR..',
    '............',
    '............',
  ],
  '👑': [
    '............',
    '............',
    '.y...y...y..',
    '.yy.yyy.yy..',
    '.yyyyyyyyy..',
    '.yyryyyryy..',
    '.yyyyyyyyy..',
    '.YYYYYYYYY..',
    '............',
    '............',
    '............',
    '............',
  ],
  '⚡': [
    '............',
    '.......yy...',
    '......yy....',
    '.....yyy....',
    '....yyy.....',
    '...yyyyyy...',
    '.....yyy....',
    '....yyy.....',
    '....yy......',
    '...yy.......',
    '...y........',
    '............',
  ],
  '💰': [
    '............',
    '....yyyy....',
    '...yyyyyy...',
    '..yywyyyYy..',
    '..ywyYYyYy..',
    '..yyyYyyYy..',
    '..yyyYYyYy..',
    '..yyyyyYYy..',
    '...YyyyyY...',
    '....YYYY....',
    '............',
    '............',
  ],
  '🔥': [
    '............',
    '.....r......',
    '....rr..r...',
    '...rrr.rr...',
    '..rrroorr...',
    '..rrooorrr..',
    '.rrooyyoorr.',
    '.rroyyyyorr.',
    '.rroyyyyorr.',
    '..rrooooor..',
    '...rrrrrr...',
    '............',
  ],
  '💧': [
    '............',
    '.....b......',
    '.....b......',
    '....bbb.....',
    '....bbb.....',
    '...bbbbb....',
    '..bcbbbbb...',
    '..bcbbbbb...',
    '..bbcbbbB...',
    '...bbbbB....',
    '....BBB.....',
    '............',
  ],
  '🌿': [
    '............',
    '.......GGG..',
    '......GGGG..',
    '.....GGGGE..',
    '..GG.GGGE...',
    '.GGGGGGE....',
    '.GGGGEE.....',
    '..EEE.E.....',
    '.....E......',
    '....E.......',
    '...E........',
    '............',
  ],
  '⭐': [
    '............',
    '.....yy.....',
    '.....yy.....',
    '....yyyy....',
    '.yyyyyyyyyy.',
    '..yyyyyyyy..',
    '...yyyyyy...',
    '...yyYYyy...',
    '..yyY..Yyy..',
    '..yY....Yy..',
    '............',
    '............',
  ],
  '🛡️': [
    '............',
    '.bbbbbbbbbb.',
    '.bwwbbbbbbb.',
    '.bwbbyybbbB.',
    '.bbbbyybbbB.',
    '.bbyyyyyybB.',
    '.bbbbyybbbB.',
    '..bbbyybbB..',
    '..bbbbbbbB..',
    '...bbbbBB...',
    '....BBBB....',
    '............',
  ],
  '🃏': [
    '............',
    '..wwwwwww...',
    '..wrwwwwwl..',
    '..wwwwwwwl..',
    '..wwwrwwwl..',
    '..wwrrrwwl..',
    '..wrrrrrwl..',
    '..wwwrwwwl..',
    '..wwwwwwwl..',
    '..wwwwwwrl..',
    '...lllllll..',
    '............',
  ],
  '💎': [
    '............',
    '............',
    '...cccccc...',
    '..cwccccbc..',
    '.cwcccccbbc.',
    '.bbbbbbbbbb.',
    '..bcbbbbBb..',
    '...bcbbBb...',
    '....bbBb....',
    '.....bb.....',
    '............',
    '............',
  ],
  '🗺️': [
    '............',
    '............',
    '.yyyyyyyyyy.',
    '.yGGyyyybby.',
    '.yGGGyybbby.',
    '.yyrryyybby.',
    '.yyyrryyyyy.',
    '.yGyyrrrGGy.',
    '.yGGyyyyGGy.',
    '.YYYYYYYYYY.',
    '............',
    '............',
  ],
  '📚': [
    '............',
    '............',
    '..rrrrrrrr..',
    '..RwwwwwwR..',
    '.bbbbbbbbb..',
    '.BwwwwwwwB..',
    '..GGGGGGGG..',
    '..EwwwwwwE..',
    '.yyyyyyyyy..',
    '.YwwwwwwwY..',
    '............',
    '............',
  ],

  /* ---------- card art ---------- */
  '☀️': [
    '............',
    '.....y......',
    '.y...y...y..',
    '..y.yyy.y...',
    '...yyyyy....',
    '.yyyyoyyyyy.',
    '...yyyyy....',
    '..y.yyy.y...',
    '.y...y...y..',
    '.....y......',
  ],
  '🌞': [
    '............',
    '..y..yy..y..',
    '...yyyyyy...',
    '..yyyyyyyy..',
    '.yyykyykyyy.',
    '.yyyyyyyyyy.',
    '..yyrrrryy..',
    '...yyyyyy...',
    '..y..yy..y..',
  ],
  '☄️': [
    '............',
    '..........r.',
    '.........ro.',
    '........roo.',
    '.......roo..',
    '.....ryoo...',
    '....ryyo....',
    '...yywy.....',
    '...ywwy.....',
    '....yy......',
  ],
  '☠️': [
    '............',
    '....pppp....',
    '...pppppp...',
    '...pkppkp...',
    '...pppppp...',
    '....pkkp....',
    '.w..pppp..w.',
    '..ww....ww..',
    '....wwww....',
    '..ww....ww..',
    '.w........w.',
  ],
  '♨️': [
    '............',
    '...r..r..r..',
    '..r..r..r...',
    '...r..r..r..',
    '..r..r..r...',
    '............',
    '.bbbbbbbbbb.',
    '.bccbbbbbbb.',
    '..bbbbbbbb..',
    '...BBBBBB...',
  ],
  '⭕': [
    '............',
    '............',
    '....bbbb....',
    '...bcccbb...',
    '..bc....bb..',
    '..bc....bB..',
    '..bb....bB..',
    '..bb....BB..',
    '...bbbBBB...',
    '....BBBB....',
  ],
  '🌀': [
    '............',
    '...rrrrrr...',
    '..r......r..',
    '.r..oooo..r.',
    '.r.o....o.r.',
    '.r.o.yy.o.r.',
    '.r.o..y.o.r.',
    '.r..oo..o.r.',
    '..r....o..r.',
    '...rrrr..r..',
    '.......rr...',
  ],
  '🌊': [
    '............',
    '......bbb...',
    '....bbccbb..',
    '...bbc..cb..',
    '..bbc...w...',
    '..bbc.......',
    '.bbbbc......',
    '.bbbbbc...b.',
    '.bbbbbbbbbb.',
    '.BBBBBBBBBB.',
  ],
  '🌋': [
    '............',
    '....r..r....',
    '.....ry.....',
    '....royo....',
    '....nooN....',
    '...nnnoNN...',
    '..nnnnnNNN..',
    '.nnnnnnnNNN.',
    '.nnnnnnnnNN.',
  ],
  '🌧️': [
    '............',
    '....llll....',
    '..llwwwwll..',
    '.lwwwwwwwwl.',
    '.llllllllll.',
    '............',
    '..b..b..b...',
    '.b..b..b....',
    '..b..b..b...',
    '.b..b..b....',
  ],
  '🌪️': [
    '............',
    '.rrrrrrrrrr.',
    '..oooooooo..',
    '...rrrrrr...',
    '....oooooo..',
    '.....rrrr...',
    '......oo....',
    '.....rr.....',
    '......o.....',
  ],
  '🌬️': [
    '............',
    '.......cc...',
    '.cccccc..c..',
    '........c...',
    '..ccccccc...',
    '............',
    '.ccccccccc..',
    '..........c.',
    '.cccc....c..',
    '.....ccc....',
  ],
  '🌱': [
    '............',
    '............',
    '..GG...GG...',
    '.GGGG.GGGG..',
    '.GGGGEGGGG..',
    '..GGGE.GG...',
    '.....E......',
    '.....E......',
    '...nnnnnn...',
    '..nnNNNNNn..',
    '...NNNNNN...',
  ],
  '🌳': [
    '............',
    '....GGGG....',
    '..GGGGGGGG..',
    '.GGeGGGGGGG.',
    '.GeGGGGGGEG.',
    '.GGGGGGGGEG.',
    '..GGGGGGEE..',
    '....EnnE....',
    '.....nn.....',
    '.....nN.....',
    '....nnNN....',
  ],
  '🌸': [
    '............',
    '.....uu.....',
    '....uuuu....',
    '..uu.uu.uu..',
    '.uuuuyyuuuu.',
    '.uuuyyyyuuu.',
    '..uuuyyuuu..',
    '...uu..uu...',
    '..uuu..uuu..',
    '...u....u...',
  ],
  '🍀': [
    '............',
    '...GG..GG...',
    '..GGGGGGGG..',
    '..GGeGGeGG..',
    '...GGGGGG...',
    '..GGGGGGGG..',
    '..GGeGGeGG..',
    '...GG.EGG...',
    '......E.....',
    '.....E......',
    '....E.......',
  ],
  '🍂': [
    '............',
    '.......oo...',
    '.....ooooo..',
    '....oooooo..',
    '...ooonoooo.',
    '..ooonoooo..',
    '..oonooooo..',
    '..onoooo....',
    '..noooo.....',
    '.n..........',
  ],
  '🍃': [
    '............',
    '..........G.',
    '.......GGGG.',
    '.....GGGGGE.',
    '...GGGGGGE..',
    '..GGGGGEGE..',
    '.GGGGEGGE...',
    '.GGGEGGE....',
    '..EEGEE.....',
    '.E..........',
  ],
  '🍄': [
    '............',
    '....rrrr....',
    '..rrwwrrrr..',
    '.rrwwrrrwwr.',
    '.rrrrrrrwwr.',
    '.rwwrrrrrrr.',
    '..RRRRRRRR..',
    '....wwww....',
    '....wwll....',
    '....wwll....',
    '...wwwlll...',
  ],
  '🏰': [
    '............',
    '.l.l.ll.l.l.',
    '.llllllllll.',
    '..llllllll..',
    '..lgllllgl..',
    '..llllllll..',
    '..llldddll..',
    '..lllddlll..',
    '..lllddlll..',
    '.gggggggggg.',
  ],
  '🐚': [
    '............',
    '.....uuu....',
    '....uuuuu...',
    '...uuwuuuu..',
    '..uuwuuuumu.',
    '..uwuuuumuu.',
    '.uuuuuummuu.',
    '.uuuummmuu..',
    '.uummmmuu...',
    '..uuuuuu....',
  ],
  '💚': [
    '............',
    '............',
    '..GG....GG..',
    '.GeGG..GGGG.',
    '.GeGGGGGGGG.',
    '.GGGGGGGGGE.',
    '..GGGGGGGE..',
    '...GGGGGE...',
    '....GGGE....',
    '.....GE.....',
  ],
  '💥': [
    '............',
    '.r...r....r.',
    '..r.ror..r..',
    '...rooor.r..',
    '..rooyyorr..',
    '.rroyyyyor..',
    '..roywyyorr.',
    '.rroyyyyor..',
    '..rrooooor..',
    '..r.rorr.r..',
    '.r....r...r.',
  ],
  '📈': [
    '............',
    '.wwwwwwwwww.',
    '.wwwwwwwrrw.',
    '.wwwwwwrrrw.',
    '.wwwwwrrwww.',
    '.wwrwrrwwww.',
    '.wrrrrwwwww.',
    '.wrrwwwwwww.',
    '.wwwwwwwwww.',
    '.llllllllll.',
  ],
  '🚿': [
    '............',
    '.ggg........',
    '...ggg......',
    '.....gggg...',
    '....gggggg..',
    '............',
    '....b.b.b...',
    '...b.b.b.b..',
    '....b.b.b...',
    '...b.b.b.b..',
    '....b.b.b...',
  ],
  '🦷': [
    '............',
    '..wwwwwwww..',
    '.wwwwwwwwwl.',
    '.wwwwwwwwwl.',
    '.wwwwwwwwwl.',
    '..wwwwwwwl..',
    '..wwl..wwl..',
    '..wwl..wwl..',
    '..wl....wl..',
  ],
  '🧪': [
    '............',
    '.....ll.....',
    '....llll....',
    '.....ll.....',
    '....wwww....',
    '...wppppw...',
    '...ppwppp...',
    '...pwppppP..',
    '...ppppppP..',
    '...ppppPPP..',
    '....PPPP....',
  ],
  '🧱': [
    '............',
    '............',
    '.rrrrlrrrrr.',
    '.RRRRlRRRRR.',
    '.llllllllll.',
    '.rrlrrrrlrr.',
    '.RRlRRRRlRR.',
    '.llllllllll.',
    '.rrrrlrrrrr.',
    '.RRRRlRRRRR.',
  ],
  '🫧': [
    '............',
    '......cc....',
    '.....cwcc...',
    '.....cccc...',
    '......cc....',
    '..ccc.......',
    '.cwccc......',
    '.cccccc.....',
    '.ccccc..cc..',
    '..ccc..cwcc.',
    '.......ccc..',
  ],

  /* ---------- relics and shop perks ---------- */
  '⚫': [
    '............',
    '............',
    '....dddd....',
    '..ddgddddd..',
    '.ddgddddddd.',
    '.dddddddodd.',
    '.ddddddoddd.',
    '..ddddddddd.',
    '...ddddddd..',
  ],
  '🍙': [
    '............',
    '.....ww.....',
    '....wwww....',
    '...wwwwww...',
    '..wwwwwwww..',
    '..wwwwwwwl..',
    '.wwddddddwl.',
    '.wwddddddwl.',
    '.lwddddddll.',
    '..llllllll..',
  ],
  '🍲': [
    '............',
    '...w..w.....',
    '....w..w....',
    '...w..w.....',
    '.oyoyoyoyo..',
    '.dddddddddd.',
    'd.dddddddd.d',
    '..dddddddd..',
    '..dddddddd..',
    '...dddddd...',
  ],
  '🔍': [
    '............',
    '...gggg.....',
    '..gcwccg....',
    '..gwcccg....',
    '..gccccg....',
    '...gggg.....',
    '.......nn...',
    '........nn..',
    '.........nn.',
  ],
  '🔔': [
    '............',
    '.....yy.....',
    '....yyyy....',
    '...yyyyyy...',
    '...ywyyyy...',
    '...ywyyyy...',
    '..yyyyyyyy..',
    '.yyyyyyyyyy.',
    '.YYYYYYYYYY.',
    '.....YY.....',
  ],
  '🔮': [
    '............',
    '....pppp....',
    '...pwpppp...',
    '..pwppppPp..',
    '..ppppppPp..',
    '..pppppPPp..',
    '...pppPPp...',
    '....pppp....',
    '...nnnnnn...',
    '..NNNNNNNN..',
  ],
  '🧣': [
    '............',
    '..rrrrrrrr..',
    '.rrRRRRRRrr.',
    '.rr......rr.',
    '..rrrrrrrr..',
    '.....rrR....',
    '.....rrR....',
    '.....rRr....',
    '.....rrR....',
    '.....yyy....',
    '.....y.y....',
  ],
  '❤️': [
    '............',
    '............',
    '..rr....rr..',
    '.rwrr..rrrr.',
    '.rwrrrrrrrr.',
    '.rrrrrrrrrR.',
    '..rrrrrrrR..',
    '...rrrrrR...',
    '....rrrR....',
    '.....rR.....',
  ],

  /* ---------- battle pop-ups and statuses ---------- */
  '✋': [
    '............',
    '...s.s.s....',
    '...s.s.s.s..',
    '...s.s.s.s..',
    '...sssssss..',
    '.s.sssssss..',
    '.ssssssssS..',
    '..sssssssS..',
    '...ssssSS...',
    '....sssS....',
  ],
  '⛑️': [
    '............',
    '.....g......',
    '...g.l.g....',
    '....llll....',
    '..llllllll..',
    '.llwllllllg.',
    '.lwllllllgg.',
    '.llllllllgg.',
    '.gggggggggg.',
  ],
  '🎗️': [
    '............',
    '....rrrr....',
    '...rr..rr...',
    '...rr..rr...',
    '....rrrr....',
    '....rrrr....',
    '...rr..rr...',
    '..rr....rr..',
    '.rr......rr.',
    '.R........R.',
  ],
  '🎯': [
    '............',
    '...rrrrrr...',
    '..rwwwwwwr..',
    '.rwwrrrrwwr.',
    '.rwrwwwwrwr.',
    '.rwrwrrwrwr.',
    '.rwrwrrwrwr.',
    '.rwrwwwwrwr.',
    '.rwwrrrrwwr.',
    '..rwwwwwwr..',
    '...rrrrrr...',
  ],
  '💨': [
    '............',
    '............',
    '........ll..',
    '.....lllwwl.',
    '.cc.lwwwwwl.',
    '....lwwwwl..',
    '.ccc.lllll..',
    '............',
    '..cc........',
  ],
  '💪': [
    '............',
    '..ss........',
    '.ssss.......',
    '.sSss.......',
    '..sss..sss..',
    '..sss.sssss.',
    '..ssssssSss.',
    '..sssssSSss.',
    '...ssssssS..',
    '....SSSSS...',
  ],
  '😡': [
    '............',
    '...rrrrrr...',
    '..rrrrrrrr..',
    '.rkrrrrrrkr.',
    '.rrkkrrkkrr.',
    '.rrkrrrrkrr.',
    '.rrrrrrrrrr.',
    '.rrrkkkkrrr.',
    '..rkrrrrkr..',
    '...rrrrrr...',
  ],
  '🩸': [
    '............',
    '.....r......',
    '.....r......',
    '....rrr.....',
    '....rrr.....',
    '...rrrrr....',
    '..rwrrrrr...',
    '..rwrrrrr...',
    '..rrwrrrR...',
    '...rrrrR....',
    '....RRR.....',
  ],
  '🗂️': [
    '............',
    '............',
    '.nnn........',
    '.nnnnnnnnnn.',
    '.yyyyyyyyyy.',
    '.yyyyyyyyyy.',
    '.yyyyyyyyyy.',
    '.yyyyyyyyyy.',
    '.YYYYYYYYYY.',
  ],
  '✨': [
    '............',
    '....y.......',
    '....y.......',
    '..yyyyy.....',
    '....y....w..',
    '....y...www.',
    '.........w..',
    '.....w......',
    '....www.....',
    '.....w......',
  ],

  /* ---------- menus, guide and windows ---------- */
  '🏠': [
    '............',
    '.....rr.....',
    '....rrrr....',
    '...rrrrrr...',
    '..rrrrrrrr..',
    '.RRRRRRRRRR.',
    '..wwwwwwww..',
    '..wbbwwnnw..',
    '..wbbwwnnw..',
    '..wwwwwnnw..',
  ],
  '📊': [
    '............',
    '.wwwwwwwwww.',
    '.wwwwwwwGGw.',
    '.wwwwwwwGGw.',
    '.wwwwbbwGGw.',
    '.wwwwbbwGGw.',
    '.wrrwbbwGGw.',
    '.wrrwbbwGGw.',
    '.wwwwwwwwww.',
    '.llllllllll.',
  ],
  '🏆': [
    '............',
    '..yyyyyyyy..',
    'y.ywyyyyyY.y',
    'y.ywyyyyyY.y',
    '.yyyyyyyyYy.',
    '..yyyyyyYY..',
    '....yyYY....',
    '.....yY.....',
    '....yyYY....',
    '...YYYYYY...',
  ],
  '🔊': [
    '............',
    '......d.....',
    '.....dd..w..',
    '..dddgd.w.w.',
    '..dgggd...w.',
    '..dgggd...w.',
    '..dddgd.w.w.',
    '.....dd..w..',
    '......d.....',
  ],
  '🔇': [
    '............',
    '......d.....',
    '.....dd.....',
    '..dddgd.r.r.',
    '..dgggd..r..',
    '..dgggd.r.r.',
    '..dddgd.....',
    '.....dd.....',
    '......d.....',
  ],
  '❓': [
    '............',
    '....rrrr....',
    '...rr..rr...',
    '.......rr...',
    '......rr....',
    '.....rr.....',
    '.....rr.....',
    '............',
    '.....rr.....',
    '.....rr.....',
  ],
  'ℹ️': [
    '............',
    '.bbbbbbbbbb.',
    '.bbbbwwbbbb.',
    '.bbbbwwbbbb.',
    '.bbbbbbbbbb.',
    '.bbbwwwbbbb.',
    '.bbbbwwbbbb.',
    '.bbbbwwbbbb.',
    '.bbbwwwwbbb.',
    '.BBBBBBBBBB.',
  ],
  '📖': [
    '............',
    '............',
    '.wwww..wwww.',
    '.wlllwwlllw.',
    '.wwwwwwwwww.',
    '.wlllwwlllw.',
    '.wwwwwwwwww.',
    '.wllwwwwllw.',
    '.wwwwwwwwww.',
    '..BBBBBBBB..',
  ],
  '🧭': [
    '............',
    '....yyyy....',
    '...ywwwwy...',
    '..ywwwrwwy..',
    '..ywwrrwwy..',
    '..ywwllwwy..',
    '..ywwlwwwy..',
    '...ywwwwy...',
    '....yyyy....',
  ],
  '👀': [
    '............',
    '............',
    '.wwww..wwww.',
    '.wwww..wwww.',
    '.wkkw..wkkw.',
    '.wkkw..wkkw.',
    '.wwww..wwww.',
  ],
  '🔒': [
    '............',
    '....llll....',
    '...l....l...',
    '...l....l...',
    '..yyyyyyyy..',
    '..yyyyyyyY..',
    '..yyykkyyY..',
    '..yyykkyyY..',
    '..yyyyyyyY..',
    '..YYYYYYYY..',
  ],
  '🔓': [
    '............',
    '.......llll.',
    '......l....l',
    '......l....l',
    '..yyyyyyyy..',
    '..yyyyyyyY..',
    '..yyykkyyY..',
    '..yyykkyyY..',
    '..yyyyyyyY..',
    '..YYYYYYYY..',
  ],
  '✅': [
    '............',
    '.GGGGGGGGGG.',
    '.GGGGGGGGwG.',
    '.GGGGGGGwwG.',
    '.GGGGGGwwGG.',
    '.GwGGGwwGGG.',
    '.GwwGwwGGGG.',
    '.GGwwwGGGGG.',
    '.GGGwGGGGGG.',
    '.EEEEEEEEEE.',
  ],
};

/** Turn a pixel map into SVG markup: each run of one colour in a row is one rect, plus the outline. */
function toSvg(drawing) {
  const rows = Array.from({ length: 12 }, (_, y) => (drawing[y] ?? '').padEnd(12, '.').slice(0, 12));
  const filled = (x, y) => (rows[y]?.[x] ?? '.') !== '.';
  const cells = rows.map((row, y) => [...row].map((ch, x) => {
    if (ch !== '.') return ch;
    return [[1, 0], [-1, 0], [0, 1], [0, -1]].some(([dx, dy]) => filled(x + dx, y + dy)) ? 'k' : '.';
  }));
  let rects = '';
  cells.forEach((row, y) => {
    for (let x = 0; x < row.length;) {
      let n = 1;
      while (row[x + n] === row[x]) n++;
      if (row[x] !== '.') rects += `<rect x="${x}" y="${y}" width="${n}" height="1" fill="${PALETTE[row[x]]}"/>`;
      x += n;
    }
  });
  return `<svg class="px-icon" viewBox="0 0 12 12" shape-rendering="crispEdges" aria-hidden="true">${rects}</svg>`;
}

const bare = (emoji) => emoji.replace(/️/g, '');
const SVGS = Object.fromEntries(Object.entries(ICONS).map(([emoji, rows]) => [bare(emoji), toSvg(rows)]));
const escape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const FIND = new RegExp(`(${Object.keys(SVGS).map(escape).join('|')})\\uFE0F?`, 'u');

/** The pixel icon for an emoji, as SVG markup (or null if it hasn't been drawn yet). */
export const pixelIcon = (emoji) => SVGS[bare(emoji)] ?? null;

function swapText(node) {
  const text = node.nodeValue;
  const match = FIND.exec(text);
  if (!match) return;
  const icon = document.createElement('span');
  icon.className = 'px-wrap';
  icon.setAttribute('role', 'img');
  icon.setAttribute('aria-label', match[1]);
  icon.innerHTML = SVGS[match[1]];
  const rest = node.splitText(match.index);
  rest.nodeValue = rest.nodeValue.slice(match[0].length);
  rest.before(icon);
  swapText(rest);
}

function swapIn(root) {
  if (root.nodeType === Node.TEXT_NODE) return swapText(root);
  if (root.nodeType !== Node.ELEMENT_NODE || root.closest('script, style, textarea, title, svg')) return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const texts = [];
  while (walker.nextNode()) texts.push(walker.currentNode);
  texts.forEach(swapText);
}

export function initPixelIcons() {
  swapIn(document.body);
  new MutationObserver((changes) => {
    for (const change of changes) {
      if (change.type === 'characterData') swapText(change.target);
      else change.addedNodes.forEach(swapIn);
    }
  }).observe(document.body, { childList: true, subtree: true, characterData: true });
}
