/* ============================================================
   icons.js  -  8-bit pixel icons that stand in for emoji.

   Each icon is a 12x12 pixel map using the letters in PALETTE
   ('.' is see-through). A black outline is added automatically
   around the filled pixels, so a map only needs the colours.

   initPixelIcons() watches the page and swaps every emoji that has
   an icon here for the pixel version, wherever it shows up (cards,
   windows, toasts...), so the data files can keep using emoji.
   Emoji without an icon yet are left alone.
   ============================================================ */

const PALETTE = {
  k: '#181010', w: '#f8f8f8', l: '#c8c8d0', g: '#888890', d: '#505058',
  r: '#e83828', R: '#a01818', o: '#f89030', y: '#f8d030', Y: '#c88810',
  G: '#58d048', E: '#208030', b: '#3878f0', B: '#1848a0', c: '#98d8f8',
  p: '#b058d8', P: '#6a2890', n: '#b06830', N: '#683818', m: '#f878b0',
  s: '#f8b888', S: '#c87848', e: '#a0e878', u: '#f8a8c8',
};

const ICONS = {
  '⚔️': [
    '............',
    '.w........w.',
    '.lw......wl.',
    '..lw....wl..',
    '...lw..wl...',
    '....lwwl....',
    '....wllw....',
    '...yl..ly...',
    '..Nyy..yyN..',
    '.NN......NN.',
    '.N........N.',
    '............',
  ],
  '💀': [
    '............',
    '...wwwwww...',
    '..wwwwwwww..',
    '.wwwwwwwwwl.',
    '.wkkwwwkkwl.',
    '.wkkwwwkkwl.',
    '.wwwwkwwwwl.',
    '..wwwwwwwl..',
    '...wkwkwk...',
    '...wwwwww...',
    '............',
    '............',
  ],
  '🏥': [   /* the map's Pokémon Center: a Poké Ball with a gold star */
    '...rrrrrr...',
    '..rrrrrrrr..',
    '.rrrrrrrrrR.',
    '.rrrrwwrrrR.',
    '.wwwwrrwwww.',
    '.RrrrwwrrrR.',
    '.RRrrrrrrRR.',
    '..RRRRRRRR..',
    '...RRyyRR...',
    '...yyyyyy...',
    '....yyYY....',
    '....y..Y....',
  ],
  '🏨': [   /* the Pokémon Center building (its bigger icon): Poké Ball sign on the red roof, glass doors */
    '............',
    '..RRRRRRRR..',
    '.RrrrwwrrrR.',
    'RrrrwrrwrrrR',
    'RRRRwwwwRRRR',
    '.wwwwwwwwww.',
    '.wcwwwwwwcw.',
    '.wwwbccbwww.',
    '.wwwbccbwww.',
    '.lllbccblll.',
    '............',
    '............',
  ],
  '🎁': [
    '............',
    '..yy....yy..',
    '...yy..yy...',
    '.rrrryyrrrr.',
    '.RRRRyyRRRR.',
    '............',
    '..rrryyrrr..',
    '..rrryyrrr..',
    '..rrryyrrr..',
    '..RRRyyRRR..',
    '............',
    '............',
  ],
  '👹': [   // bosses: a spiky horned face in a red ring
    '...rrrrrr...',
    '..rkkkkkkr..',
    '.rkrkkkkrkr.',
    'rkkrrrrrrkkr',
    'rkrrkrrkrrkr',
    'rkrrrRRrrrkr',
    'rkkrkrrkrkkr',
    'rkkrrkkrrkkr',
    '.rkkrrrrkkr.',
    '.rkrkkkkrkr.',
    '..rkkrrkkr..',
    '...rrrrrr...',
  ],
  '👑': [
    '............',
    '............',
    '.y...y...y..',
    '.yy.yyy.yy..',
    '.yyyyyyyyy..',
    '.yyryyyryy..',
    '.yyyyyyyyy..',
    '.YYYYYYYYY..',
    '............',
    '............',
    '............',
    '............',
  ],
  '⚡': [
    '............',
    '.......yy...',
    '......yy....',
    '.....yyy....',
    '....yyy.....',
    '...yyyyyy...',
    '.....yyy....',
    '....yyy.....',
    '....yy......',
    '...yy.......',
    '...y........',
    '............',
  ],
  '💰': [
    '............',
    '....yyyy....',
    '...yyyyyy...',
    '..yywyyyYy..',
    '..ywyYYyYy..',
    '..yyyYyyYy..',
    '..yyyYYyYy..',
    '..yyyyyYYy..',
    '...YyyyyY...',
    '....YYYY....',
    '............',
    '............',
  ],
  '💴': [
    '............',
    '............',
    '............',
    '.EEEEEEEEEE.',
    '.EeeeeeeeeE.',
    '.EeGeyyeGeE.',
    '.EeeyYYyeeE.',
    '.EeGeyyeGeE.',
    '.EeeeeeeeeE.',
    '.EEEEEEEEEE.',
    '............',
    '............',
  ],
  '🏪': [
    '............',
    '....bbbb....',
    '..bbbbbbbb..',
    '.BBBBBBBBBB.',
    '.wwwwwwwwww.',
    '.wccwwwwccw.',
    '.wccwbbwccw.',
    '.wwwwbbwwww.',
    '.wwwwkkwwww.',
    '.llllkkllll.',
    '............',
    '............',
  ],
  '🪙': [
    '...N....N...',
    '....N..N....',
    '.....NN.....',
    '....yyyy....',
    '...yyYYyy...',
    '..yyYyyYyy..',
    '..yYywyyYy..',
    '..yYyyyyYy..',
    '..yyYyyYyy..',
    '...yyYYyy...',
    '....yyyy....',
    '............',
  ],
  '🔥': [
    '............',
    '.....r......',
    '....rr..r...',
    '...rrr.rr...',
    '..rrroorr...',
    '..rrooorrr..',
    '.rrooyyoorr.',
    '.rroyyyyorr.',
    '.rroyyyyorr.',
    '..rrooooor..',
    '...rrrrrr...',
    '............',
  ],
  '💧': [
    '............',
    '.....b......',
    '.....b......',
    '....bbb.....',
    '....bbb.....',
    '...bbbbb....',
    '..bcbbbbb...',
    '..bcbbbbb...',
    '..bbcbbbB...',
    '...bbbbB....',
    '....BBB.....',
    '............',
  ],
  '🌿': [
    '............',
    '..........G.',
    '........eGG.',
    '......eGGEG.',
    '.....eGGEGG.',
    '....eGGEGGE.',
    '...eGGEGGGE.',
    '...GGEGGGE..',
    '..GGEGGGE...',
    '..GEEEEE....',
    '.EE.........',
    '.E..........',
  ],
  '🔯': [   // the Neutral type: a black six-pointed star on a shaded silver disc
    '....gggg....',
    '..gglkklgg..',
    '.gllwkkwllg.',
    '.kklwkkwlkk.',
    'gllkkkkkkllg',
    'glwwkkkkwwlg',
    'glwwkkkkwwlg',
    'gllkkkkkkllg',
    '.kklwkkwlkk.',
    '.gllwkkwllg.',
    '..gglkklgg..',
    '....gggg....',
  ],
  '⭐': [
    '............',
    '.....yy.....',
    '.....yy.....',
    '....yyyy....',
    '.yyyyyyyyyy.',
    '..yyyyyyyy..',
    '...yyyyyy...',
    '...yyYYyy...',
    '..yyY..Yyy..',
    '..yY....Yy..',
    '............',
    '............',
  ],
  '🛡️': [
    '............',
    '.bbbbbbbbbb.',
    '.bwwbbbbbbb.',
    '.bwbbyybbbB.',
    '.bbbbyybbbB.',
    '.bbyyyyyybB.',
    '.bbbbyybbbB.',
    '..bbbyybbB..',
    '..bbbbbbbB..',
    '...bbbbBB...',
    '....BBBB....',
    '............',
  ],
  '🃏': [
    '............',
    '..wwwwwww...',
    '..wrwwwwwl..',
    '..wwwwwwwl..',
    '..wwwrwwwl..',
    '..wwrrrwwl..',
    '..wrrrrrwl..',
    '..wwwrwwwl..',
    '..wwwwwwwl..',
    '..wwwwwwrl..',
    '...lllllll..',
    '............',
  ],
  '💎': [
    '............',
    '............',
    '...cccccc...',
    '..cwccccbc..',
    '.cwcccccbbc.',
    '.bbbbbbbbbb.',
    '..bcbbbbBb..',
    '...bcbbBb...',
    '....bbBb....',
    '.....bb.....',
    '............',
    '............',
  ],
  '🗺️': [
    '............',
    '............',
    '.yyyyyyyyyy.',
    '.yGGyyyybby.',
    '.yGGGyybbby.',
    '.yyrryyybby.',
    '.yyyrryyyyy.',
    '.yGyyrrrGGy.',
    '.yGGyyyyGGy.',
    '.YYYYYYYYYY.',
    '............',
    '............',
  ],
  '📚': [   // the draw pile: a stack of face-down cards with a Poké Ball back
    '............',
    '.kkkkkkkk...',
    '.krrrrrrkkk.',
    '.krrrrrrklk.',
    '.krrrrrrklk.',
    '.kkkwwkkklk.',
    '.kwwwwwwklk.',
    '.kwwwwwwklk.',
    '.kwwwwwwklk.',
    '.kkkkkkkklk.',
    '...kkkkkkkk.',
    '............',
  ],

  /* ---------- card art ---------- */
  '☀️': [
    '............',
    '.....y......',
    '.y...y...y..',
    '..y.yyy.y...',
    '...yyyyy....',
    '.yyyyoyyyyy.',
    '...yyyyy....',
    '..y.yyy.y...',
    '.y...y...y..',
    '.....y......',
  ],
  '🌞': [
    '............',
    '..y..yy..y..',
    '...yyyyyy...',
    '..yyyyyyyy..',
    '.yyykyykyyy.',
    '.yyyyyyyyyy.',
    '..yyrrrryy..',
    '...yyyyyy...',
    '..y..yy..y..',
  ],
  '☄️': [
    '............',
    '..........r.',
    '.........ro.',
    '........roo.',
    '.......roo..',
    '.....ryoo...',
    '....ryyo....',
    '...yywy.....',
    '...ywwy.....',
    '....yy......',
  ],
  '☠️': [
    '............',
    '....pppp....',
    '...pppppp...',
    '...pkppkp...',
    '...pppppp...',
    '....pkkp....',
    '.w..pppp..w.',
    '..ww....ww..',
    '....wwww....',
    '..ww....ww..',
    '.w........w.',
  ],
  '♨️': [
    '............',
    '...r..r..r..',
    '..r..r..r...',
    '...r..r..r..',
    '..r..r..r...',
    '............',
    '.bbbbbbbbbb.',
    '.bccbbbbbbb.',
    '..bbbbbbbb..',
    '...BBBBBB...',
  ],
  '⭕': [
    '............',
    '............',
    '....bbbb....',
    '...bcccbb...',
    '..bc....bb..',
    '..bc....bB..',
    '..bb....bB..',
    '..bb....BB..',
    '...bbbBBB...',
    '....BBBB....',
  ],
  '🌀': [
    '............',
    '...rrrrrr...',
    '..r......r..',
    '.r..oooo..r.',
    '.r.o....o.r.',
    '.r.o.yy.o.r.',
    '.r.o..y.o.r.',
    '.r..oo..o.r.',
    '..r....o..r.',
    '...rrrr..r..',
    '.......rr...',
  ],
  '🌊': [
    '............',
    '......bbb...',
    '....bbccbb..',
    '...bbc..cb..',
    '..bbc...w...',
    '..bbc.......',
    '.bbbbc......',
    '.bbbbbc...b.',
    '.bbbbbbbbbb.',
    '.BBBBBBBBBB.',
  ],
  '🌋': [
    '............',
    '....r..r....',
    '.....ry.....',
    '....royo....',
    '....nooN....',
    '...nnnoNN...',
    '..nnnnnNNN..',
    '.nnnnnnnNNN.',
    '.nnnnnnnnNN.',
  ],
  '🌧️': [
    '............',
    '....llll....',
    '..llwwwwll..',
    '.lwwwwwwwwl.',
    '.llllllllll.',
    '............',
    '..b..b..b...',
    '.b..b..b....',
    '..b..b..b...',
    '.b..b..b....',
  ],
  '🌪️': [
    '............',
    '.rrrrrrrrrr.',
    '..oooooooo..',
    '...rrrrrr...',
    '....oooooo..',
    '.....rrrr...',
    '......oo....',
    '.....rr.....',
    '......o.....',
  ],
  '🌬️': [
    '............',
    '.......cc...',
    '.cccccc..c..',
    '........c...',
    '..ccccccc...',
    '............',
    '.ccccccccc..',
    '..........c.',
    '.cccc....c..',
    '.....ccc....',
  ],
  '🌱': [
    '............',
    '............',
    '..GG...GG...',
    '.GGGG.GGGG..',
    '.GGGGEGGGG..',
    '..GGGE.GG...',
    '.....E......',
    '.....E......',
    '...nnnnnn...',
    '..nnNNNNNn..',
    '...NNNNNN...',
  ],
  '🌳': [
    '............',
    '....GGGG....',
    '..GGGGGGGG..',
    '.GGeGGGGGGG.',
    '.GeGGGGGGEG.',
    '.GGGGGGGGEG.',
    '..GGGGGGEE..',
    '....EnnE....',
    '.....nn.....',
    '.....nN.....',
    '....nnNN....',
  ],
  '🌸': [
    '............',
    '.....uu.....',
    '....uuuu....',
    '..uu.uu.uu..',
    '.uuuuyyuuuu.',
    '.uuuyyyyuuu.',
    '..uuuyyuuu..',
    '...uu..uu...',
    '..uuu..uuu..',
    '...u....u...',
  ],
  '🍀': [
    '............',
    '...GG..GG...',
    '..GGGGGGGG..',
    '..GGeGGeGG..',
    '...GGGGGG...',
    '..GGGGGGGG..',
    '..GGeGGeGG..',
    '...GG.EGG...',
    '......E.....',
    '.....E......',
    '....E.......',
  ],
  '🍂': [
    '............',
    '.......oo...',
    '.....ooooo..',
    '....oooooo..',
    '...ooonoooo.',
    '..ooonoooo..',
    '..oonooooo..',
    '..onoooo....',
    '..noooo.....',
    '.n..........',
  ],
  '🍃': [
    '............',
    '..........G.',
    '.......GGGG.',
    '.....GGGGGE.',
    '...GGGGGGE..',
    '..GGGGGEGE..',
    '.GGGGEGGE...',
    '.GGGEGGE....',
    '..EEGEE.....',
    '.E..........',
  ],
  '🍄': [
    '............',
    '....rrrr....',
    '..rrwwrrrr..',
    '.rrwwrrrwwr.',
    '.rrrrrrrwwr.',
    '.rwwrrrrrrr.',
    '..RRRRRRRR..',
    '....wwww....',
    '....wwll....',
    '....wwll....',
    '...wwwlll...',
  ],
  '🏰': [
    '............',
    '.l.l.ll.l.l.',
    '.llllllllll.',
    '..llllllll..',
    '..lgllllgl..',
    '..llllllll..',
    '..llldddll..',
    '..lllddlll..',
    '..lllddlll..',
    '.gggggggggg.',
  ],
  '🐚': [
    '............',
    '.....uuu....',
    '....uuuuu...',
    '...uuwuuuu..',
    '..uuwuuuumu.',
    '..uwuuuumuu.',
    '.uuuuuummuu.',
    '.uuuummmuu..',
    '.uummmmuu...',
    '..uuuuuu....',
  ],
  '💚': [
    '............',
    '............',
    '..GG....GG..',
    '.GeGG..GGGG.',
    '.GeGGGGGGGG.',
    '.GGGGGGGGGE.',
    '..GGGGGGGE..',
    '...GGGGGE...',
    '....GGGE....',
    '.....GE.....',
  ],
  '💥': [
    '............',
    '.r...r....r.',
    '..r.ror..r..',
    '...rooor.r..',
    '..rooyyorr..',
    '.rroyyyyor..',
    '..roywyyorr.',
    '.rroyyyyor..',
    '..rrooooor..',
    '..r.rorr.r..',
    '.r....r...r.',
  ],
  '📈': [
    '............',
    '.wwwwwwwwww.',
    '.wwwwwwwrrw.',
    '.wwwwwwrrrw.',
    '.wwwwwrrwww.',
    '.wwrwrrwwww.',
    '.wrrrrwwwww.',
    '.wrrwwwwwww.',
    '.wwwwwwwwww.',
    '.llllllllll.',
  ],
  '🚿': [
    '............',
    '.ggg........',
    '...ggg......',
    '.....gggg...',
    '....gggggg..',
    '............',
    '....b.b.b...',
    '...b.b.b.b..',
    '....b.b.b...',
    '...b.b.b.b..',
    '....b.b.b...',
  ],
  '🦷': [
    '............',
    '..wwwwwwww..',
    '.wwwwwwwwwl.',
    '.wwwwwwwwwl.',
    '.wwwwwwwwwl.',
    '..wwwwwwwl..',
    '..wwl..wwl..',
    '..wwl..wwl..',
    '..wl....wl..',
  ],
  '🧪': [
    '............',
    '.....ll.....',
    '....llll....',
    '.....ll.....',
    '....wwww....',
    '...wppppw...',
    '...ppwppp...',
    '...pwppppP..',
    '...ppppppP..',
    '...ppppPPP..',
    '....PPPP....',
  ],
  '🧱': [
    '............',
    '............',
    '.rrrrlrrrrr.',
    '.RRRRlRRRRR.',
    '.llllllllll.',
    '.rrlrrrrlrr.',
    '.RRlRRRRlRR.',
    '.llllllllll.',
    '.rrrrlrrrrr.',
    '.RRRRlRRRRR.',
  ],
  '🫧': [
    '............',
    '......cc....',
    '.....cwcc...',
    '.....cccc...',
    '......cc....',
    '..ccc.......',
    '.cwccc......',
    '.cccccc.....',
    '.ccccc..cc..',
    '..ccc..cwcc.',
    '.......ccc..',
  ],

  /* ---------- relics and shop perks ---------- */
  '⚫': [
    '............',
    '............',
    '....dddd....',
    '..ddgddddd..',
    '.ddgddddddd.',
    '.dddddddodd.',
    '.ddddddoddd.',
    '..ddddddddd.',
    '...ddddddd..',
  ],
  '🍙': [
    '............',
    '.....ww.....',
    '....wwww....',
    '...wwwwww...',
    '..wwwwwwww..',
    '..wwwwwwwl..',
    '.wwddddddwl.',
    '.wwddddddwl.',
    '.lwddddddll.',
    '..llllllll..',
  ],
  '🍲': [
    '............',
    '...w..w.....',
    '....w..w....',
    '...w..w.....',
    '.oyoyoyoyo..',
    '.dddddddddd.',
    'd.dddddddd.d',
    '..dddddddd..',
    '..dddddddd..',
    '...dddddd...',
  ],
  '🔍': [
    '............',
    '...gggg.....',
    '..gcwccg....',
    '..gwcccg....',
    '..gccccg....',
    '...gggg.....',
    '.......nn...',
    '........nn..',
    '.........nn.',
  ],
  '🔔': [
    '............',
    '.....yy.....',
    '....yyyy....',
    '...yyyyyy...',
    '...ywyyyy...',
    '...ywyyyy...',
    '..yyyyyyyy..',
    '.yyyyyyyyyy.',
    '.YYYYYYYYYY.',
    '.....YY.....',
  ],
  '🔮': [
    '............',
    '....pppp....',
    '...pwpppp...',
    '..pwppppPp..',
    '..ppppppPp..',
    '..pppppPPp..',
    '...pppPPp...',
    '....pppp....',
    '...nnnnnn...',
    '..NNNNNNNN..',
  ],
  '🧣': [
    '............',
    '..rrrrrrrr..',
    '.rrRRRRRRrr.',
    '.rr......rr.',
    '..rrrrrrrr..',
    '.....rrR....',
    '.....rrR....',
    '.....rRr....',
    '.....rrR....',
    '.....yyy....',
    '.....y.y....',
  ],
  '🥋': [
    '............',
    '...ww..ww...',
    '..wwwwwwww..',
    '.wwwwwwwwww.',
    '.wwlwwwwlww.',
    '..wlwwwwlw..',
    '..wkkkkkkw..',
    '..wwwkkwww..',
    '..wwkwwkww..',
    '..wwk..kww..',
    '..ll....ll..',
  ],
  '🐾': [
    '............',
    '..n......n..',
    '..nn....nn..',
    '..nnn..nnn..',
    '...nn..nn...',
    '............',
    '....nnnn....',
    '...nnnnnn...',
    '..nnnnnnnn..',
    '..nnNNNNnn..',
    '...nn..nn...',
  ],
  '🏷️': [
    '............',
    '.....yyyyyy.',
    '....yyyyyyy.',
    '...yywyyyyy.',
    '..yyyyyyyyy.',
    '.yyyrrrryyy.',
    '..yyyyyyyyy.',
    '...yyrrryyy.',
    '....yyyyyyy.',
    '.....YYYYYY.',
  ],
  '🦀': [
    '............',
    '.r.r....r.r.',
    '.rrr....rrr.',
    '..r......r..',
    '..r.w..w.r..',
    '..rrrrrrrr..',
    '.rrrrrrrrrr.',
    '.rRrrrrrrRr.',
    '..RRRRRRRR..',
    '.R.R....R.R.',
  ],
  '🎒': [
    '............',
    '....nnnn....',
    '...n....n...',
    '..oooooooo..',
    '.oooooooooo.',
    '.oSSSSSSSSo.',
    '.oSyyyyyySo.',
    '.ooooyyoooo.',
    '.oooooooooo.',
    '.oooooooooo.',
    '..SSSSSSSS..',
  ],
  '🎀': [
    '............',
    '............',
    '.mm......mm.',
    '.mmmm..mmmm.',
    '.mmumrrmumm.',
    '.mmmmrrmmmm.',
    '.mmmm..mmmm.',
    '.mm.m..m.mm.',
    '....m..m....',
    '...mm..mm...',
  ],
  '👓': [
    '............',
    '............',
    '............',
    '.dddd..dddd.',
    'dccwcddccwcd',
    'dcccc..ccccd',
    'dcccc..ccccd',
    '.dddd..dddd.',
  ],
  '❤️': [
    '............',
    '............',
    '..rr....rr..',
    '.rwrr..rrrr.',
    '.rwrrrrrrrr.',
    '.rrrrrrrrrR.',
    '..rrrrrrrR..',
    '...rrrrrR...',
    '....rrrR....',
    '.....rR.....',
  ],

  /* ---------- battle pop-ups and statuses ---------- */
  '✋': [
    '............',
    '...s.s.s....',
    '...s.s.s.s..',
    '...s.s.s.s..',
    '...sssssss..',
    '.s.sssssss..',
    '.ssssssssS..',
    '..sssssssS..',
    '...ssssSS...',
    '....sssS....',
  ],
  '⛑️': [
    '............',
    '.....g......',
    '...g.l.g....',
    '....llll....',
    '..llllllll..',
    '.llwllllllg.',
    '.lwllllllgg.',
    '.llllllllgg.',
    '.gggggggggg.',
  ],
  '🎗️': [
    '............',
    '....rrrr....',
    '...rr..rr...',
    '...rr..rr...',
    '....rrrr....',
    '....rrrr....',
    '...rr..rr...',
    '..rr....rr..',
    '.rr......rr.',
    '.R........R.',
  ],
  '🎯': [
    '............',
    '...rrrrrr...',
    '..rwwwwwwr..',
    '.rwwrrrrwwr.',
    '.rwrwwwwrwr.',
    '.rwrwrrwrwr.',
    '.rwrwrrwrwr.',
    '.rwrwwwwrwr.',
    '.rwwrrrrwwr.',
    '..rwwwwwwr..',
    '...rrrrrr...',
  ],
  '🎰': [   // the Game Corner (the home shop): a slot machine showing three 7s, pull lever on the right
    'yyyyyyyyyy..',
    'yPPPPPPPPy..',
    'pppppppppp.r',
    'pwwpwwpwwp.l',
    'prwprwprwp.l',
    'pwwpwwpwwp.l',
    'pppppppppppl',
    'pYYYYYYYYp..',
    'pYkkkkkkYp..',
    'pppppppppp..',
    'PPPPPPPPPP..',
    '............',
  ],
  '📉': [   // Weakened: a sword and the games' blue stat-down arrow
    '..w.........',
    '.lw.....bb..',
    '.lw.....bb..',
    '.lw.....bb..',
    '.lw.....bb..',
    '.lw.....bb..',
    '.lw...bbbbbb',
    'yyyy...bbbb.',
    '.NN.....bb..',
    '.NN.........',
    '.yy.........',
    '............',
  ],
  '💨': [
    '............',
    '............',
    '........ll..',
    '.....lllwwl.',
    '.cc.lwwwwwl.',
    '....lwwwwl..',
    '.ccc.lllll..',
    '............',
    '..cc........',
  ],
  '👻': [
    '............',
    '....pppp....',
    '...pppppp...',
    '..pppppppp..',
    '..pwwppwwp..',
    '..pkwppkwp..',
    '..pppppppp..',
    '..pppppppp..',
    '..pppppppp..',
    '..pp.pp.pp..',
    '..p..p..p...',
  ],
  '💪': [   /* drawn as a fist: a flexed arm didn't read at this size */
    '............',
    '.ss.ss.ss...',
    '.sskssksss..',
    '.sskssksssk.',
    '.SSkSSkSSsk.',
    '.kkkkkkkssk.',
    '.sssssssssS.',
    '.sssssssssS.',
    '..SSSSssSS..',
    '...sssssS...',
    '...sssssS...',
    '............',
  ],
  '😡': [
    '............',
    '...rrrrrr...',
    '..rrrrrrrr..',
    '.rkrrrrrrkr.',
    '.rrkkrrkkrr.',
    '.rrkrrrrkrr.',
    '.rrrrrrrrrr.',
    '.rrrkkkkrrr.',
    '..rkrrrrkr..',
    '...rrrrrr...',
  ],
  '🩸': [
    '............',
    '.....r......',
    '.....r......',
    '....rrr.....',
    '....rrr.....',
    '...rrrrr....',
    '..rwrrrrr...',
    '..rwrrrrr...',
    '..rrwrrrR...',
    '...rrrrR....',
    '....RRR.....',
  ],
  '🗂️': [   // the discard pile: played cards, face up
    '............',
    '.kkkkkkk....',
    '.koooook....',
    '.kwrkkkkkkk.',
    '.kwrkoooook.',
    '.kwrkwrrrwk.',
    '.kwwkwrrrwk.',
    '.klwkwrrrwk.',
    '.klwkwwwwwk.',
    '.kkkklwlwlk.',
    '....kkkkkkk.',
  ],
  '✨': [
    '............',
    '....y.......',
    '....y.......',
    '..yyyyy.....',
    '....y....w..',
    '....y...www.',
    '.........w..',
    '.....w......',
    '....www.....',
    '.....w......',
  ],

  '⏫': [   // a permanent Game Corner perk: the games' stat-raise arrows
    '.....ee.....',
    '....eGGe....',
    '...eGGGGE...',
    '..eGGEEGGE..',
    '.eGGE..EGGE.',
    '..EE....EE..',
    '.....ee.....',
    '....eGGe....',
    '...eGGGGE...',
    '..eGGEEGGE..',
    '.eGGE..EGGE.',
    '..EE....EE..',
  ],

  /* ---------- menus, guide and windows ---------- */
  '🏠': [
    '............',
    '.....rr.....',
    '....rrrr....',
    '...rrrrrr...',
    '..rrrrrrrr..',
    '.RRRRRRRRRR.',
    '..wwwwwwww..',
    '..wbbwwnnw..',
    '..wbbwwnnw..',
    '..wwwwwnnw..',
  ],
  '📊': [
    '............',
    '.wwwwwwwwww.',
    '.wwwwwwwGGw.',
    '.wwwwwwwGGw.',
    '.wwwwbbwGGw.',
    '.wwwwbbwGGw.',
    '.wrrwbbwGGw.',
    '.wrrwbbwGGw.',
    '.wwwwwwwwww.',
    '.llllllllll.',
  ],
  '🏆': [
    '............',
    '..yyyyyyyy..',
    'y.ywyyyyyY.y',
    'y.ywyyyyyY.y',
    '.yyyyyyyyYy.',
    '..yyyyyyYY..',
    '....yyYY....',
    '.....yY.....',
    '....yyYY....',
    '...YYYYYY...',
  ],
  '🔊': [
    '............',
    '......d.....',
    '.....dd..w..',
    '..dddgd.w.w.',
    '..dgggd...w.',
    '..dgggd...w.',
    '..dddgd.w.w.',
    '.....dd..w..',
    '......d.....',
  ],
  '🔇': [
    '............',
    '......d.....',
    '.....dd.....',
    '..dddgd.r.r.',
    '..dgggd..r..',
    '..dgggd.r.r.',
    '..dddgd.....',
    '.....dd.....',
    '......d.....',
  ],
  '❓': [
    '............',
    '....rrrr....',
    '...rr..rr...',
    '.......rr...',
    '......rr....',
    '.....rr.....',
    '.....rr.....',
    '............',
    '.....rr.....',
    '.....rr.....',
  ],
  'ℹ️': [
    '............',
    '.bbbbbbbbbb.',
    '.bbbbwwbbbb.',
    '.bbbbwwbbbb.',
    '.bbbbbbbbbb.',
    '.bbbwwwbbbb.',
    '.bbbbwwbbbb.',
    '.bbbbwwbbbb.',
    '.bbbwwwwbbb.',
    '.BBBBBBBBBB.',
  ],
  '📖': [
    '............',
    '............',
    '.wwww..wwww.',
    '.wlllwwlllw.',
    '.wwwwwwwwww.',
    '.wlllwwlllw.',
    '.wwwwwwwwww.',
    '.wllwwwwllw.',
    '.wwwwwwwwww.',
    '..BBBBBBBB..',
  ],
  '🧭': [
    '............',
    '....yyyy....',
    '...ywwwwy...',
    '..ywwwrwwy..',
    '..ywwrrwwy..',
    '..ywwllwwy..',
    '..ywwlwwwy..',
    '...ywwwwy...',
    '....yyyy....',
  ],
  '👀': [
    '............',
    '............',
    '.wwww..wwww.',
    '.wwww..wwww.',
    '.wkkw..wkkw.',
    '.wkkw..wkkw.',
    '.wwww..wwww.',
  ],
  '🔒': [
    '............',
    '....llll....',
    '...l....l...',
    '...l....l...',
    '..yyyyyyyy..',
    '..yyyyyyyY..',
    '..yyykkyyY..',
    '..yyykkyyY..',
    '..yyyyyyyY..',
    '..YYYYYYYY..',
  ],
  '🔓': [
    '............',
    '.......llll.',
    '......l....l',
    '......l....l',
    '..yyyyyyyy..',
    '..yyyyyyyY..',
    '..yyykkyyY..',
    '..yyykkyyY..',
    '..yyyyyyyY..',
    '..YYYYYYYY..',
  ],
  '✅': [
    '............',
    '.GGGGGGGGGG.',
    '.GGGGGGGGwG.',
    '.GGGGGGGwwG.',
    '.GGGGGGwwGG.',
    '.GwGGGwwGGG.',
    '.GwwGwwGGGG.',
    '.GGwwwGGGGG.',
    '.GGGwGGGGGG.',
    '.EEEEEEEEEE.',
  ],
  '🫐': [   // an Oran Berry
    '............',
    '......EG....',
    '.....EGG....',
    '......E.....',
    '....bbbbb...',
    '...bcbbbbb..',
    '..bccbbbbbb.',
    '..bcbbbbbbb.',
    '..bbbbbbbbB.',
    '...bbbbbbB..',
    '....BBBBB...',
  ],
  '🎓': [
    '............',
    '.....dd.....',
    '...dddddd...',
    '.dddddddddd.',
    '...dddddd.y.',
    '....dddd..y.',
    '...gggggg.y.',
    '...gggggg.Y.',
    '....gggg....',
  ],
  '🚀': [   // Team Rocket's R
    '............',
    '..wwwwwwww..',
    '.wrrrrrrrww.',
    '.wrrwwwwrrw.',
    '.wrrwwwwrrw.',
    '.wrrrrrrrww.',
    '.wrrwwrrwww.',
    '.wrrwwwrrww.',
    '.wrrwwwwrrw.',
    '..wwwwwwww..',
  ],

  // items (js/data/items.js)
  '🧴': [   // Potion: the games' purple spray bottle
    '............',
    '.....ll.....',
    '....lwwll...',
    '.....ww.....',
    '....wwww....',
    '...pppppp...',
    '...pmppPp...',
    '...pmppPp...',
    '...ppppPp...',
    '...pppPPp...',
    '...PPPPPP...',
    '............',
  ],
  '🥤': [   // Super Potion: the yellow one
    '............',
    '.....ll.....',
    '....lwwll...',
    '.....ww.....',
    '....wwww....',
    '...yyyyyy...',
    '...ywyyYy...',
    '...ywooYy...',
    '...yyooYy...',
    '...yyyYYy...',
    '...YYYYYY...',
    '............',
  ],
  '🗡️': [   // X Attack
    '.....w......',
    '....wlw.....',
    '....wlw.....',
    '....wlw.....',
    '....wlw.....',
    '....wlw.....',
    '..rrrrrrr...',
    '..RRRrRRR...',
    '.....N......',
    '....nNn.....',
    '....yYy.....',
    '............',
  ],
  '🔰': [   // X Defend
    '............',
    '..bbbbbbbb..',
    '..bccbbbbB..',
    '..bcbbbbbB..',
    '..bbbwwbbB..',
    '..bbwwwwbB..',
    '...bbwwbB...',
    '...bbbbbB...',
    '....bbbB....',
    '.....bB.....',
    '............',
    '............',
  ],
  '👟': [   // X Speed
    '............',
    '............',
    '...rrr......',
    '...rwrr.....',
    '...rwwrr....',
    '...rrrrrr...',
    '..rrrrrrrrr.',
    '..rrwrwrwrr.',
    '..wwwwwwwww.',
    '..lllllllll.',
    '............',
    '............',
  ],
  '🏹': [   // Dire Hit: an arrow flying up and right
    '............',
    '.......wwww.',
    '........lww.',
    '.......n.lw.',
    '......n...w.',
    '.....n......',
    '....n.......',
    '.rrn........',
    '.rn.........',
    '.rr.........',
    '............',
    '............',
  ],
  '🍶': [   // Ether
    '............',
    '.....NN.....',
    '.....nn.....',
    '....cccc....',
    '....cwcc....',
    '...bbbbbb...',
    '...bcbbbB...',
    '...bcbbbB...',
    '...bbbbbB...',
    '...BBBBBB...',
    '............',
    '............',
  ],
  '🧿': [   // Guard Spec.
    '............',
    '....bbbb....',
    '...bbbbbb...',
    '..bbwwwwbb..',
    '..bwwccwwb..',
    '..bwcBBcwb..',
    '..bwcBBcwb..',
    '..bwwccwwb..',
    '..bbwwwwbb..',
    '...bbbbbb...',
    '....bbbb....',
    '............',
  ],
  '🧸': [   // Poké Doll: a Pikachu doll
    '............',
    '.k........k.',
    '.ky......yk.',
    '..yy....yy..',
    '..yyyyyyyy..',
    '.yyyyyyyyyy.',
    '.yykyyyykyy.',
    '.yyyyyyyyyy.',
    '.rryykkyyrr.',
    '..yyyyyyyy..',
    '...yyyyyy...',
    '............',
  ],
  '🥚': [
    '............',
    '.....ww.....',
    '....wwww....',
    '...wwGGww...',
    '...wwGGww...',
    '..wwwwwwww..',
    '..wGwwwGGw..',
    '..wwwwwGGl..',
    '..lwwGwwwl..',
    '...lwwwwl...',
    '....llll....',
    '............',
  ],
  '⛲': [
    '............',
    '.....cc.....',
    '....cbbc....',
    '...cb..bc...',
    '..cb.ll.bc..',
    '..c..ll..c..',
    '.....ll.....',
    '.llllllllll.',
    '.lbbcbbbcbl.',
    '.lbbbbbbbbl.',
    '.gggggggggg.',
    '............',
  ],
  '📣': [
    '............',
    '.........r..',
    '........rr..',
    '......rrwr..',
    '..yyyrrwwr..',
    '.yyyyrwwwr..',
    '.yyyyrwwwr..',
    '..yyyrrwwr..',
    '...Y..rrwr..',
    '...Y....rr..',
    '.........r..',
    '............',
  ],
  '⛩️': [
    '............',
    '.rrrrrrrrrr.',
    '..RRRRRRRR..',
    '...r....r...',
    '.rrrrrrrrrr.',
    '...r....r...',
    '...r....r...',
    '...r....r...',
    '...r....r...',
    '...r....r...',
    '..RRR..RRR..',
    '............',
  ],
  '🔴': gem('r', 'R'),   // Fire Gem
  '🟢': gem('G', 'E'),   // Grass Gem
  '🔵': gem('b', 'B'),   // Water Gem
};

/** A cut gem in one colour (A) with its shaded side (D). */
function gem(A, D) {
  return [
    '............',
    '............',
    '...AAAAAA...',
    '..AwAAAAAA..',
    '.AwAAAAAAAD.',
    '.AAAAAAAAAD.',
    '..AAAAAAAD..',
    '...AAAAAD...',
    '....AAAD....',
    '.....AD.....',
    '............',
    '............',
  ].map(row => row.replace(/A/g, A).replace(/D/g, D));
}

/** Turn a pixel map into SVG markup: each run of one colour in a row is one rect, plus the outline. */
function toSvg(drawing) {
  const rows = Array.from({ length: 12 }, (_, y) => (drawing[y] ?? '').padEnd(12, '.').slice(0, 12));
  const filled = (x, y) => (rows[y]?.[x] ?? '.') !== '.';
  const cells = rows.map((row, y) => [...row].map((ch, x) => {
    if (ch !== '.') return ch;
    return [[1, 0], [-1, 0], [0, 1], [0, -1]].some(([dx, dy]) => filled(x + dx, y + dy)) ? 'k' : '.';
  }));
  let rects = '';
  cells.forEach((row, y) => {
    for (let x = 0; x < row.length;) {
      let n = 1;
      while (row[x + n] === row[x]) n++;
      if (row[x] !== '.') rects += `<rect x="${x}" y="${y}" width="${n}" height="1" fill="${PALETTE[row[x]]}"/>`;
      x += n;
    }
  });
  return `<svg class="px-icon" viewBox="0 0 12 12" shape-rendering="crispEdges" aria-hidden="true">${rects}</svg>`;
}

const bare = (emoji) => emoji.replace(/️/g, '');
const SVGS = Object.fromEntries(Object.entries(ICONS).map(([emoji, rows]) => [bare(emoji), toSvg(rows)]));
const escape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const FIND = new RegExp(`(${Object.keys(SVGS).map(escape).join('|')})\\uFE0F?`, 'u');

/** The pixel icon for an emoji, as SVG markup (or null if it hasn't been drawn yet). */
export const pixelIcon = (emoji) => SVGS[bare(emoji)] ?? null;

function swapText(node) {
  const text = node.nodeValue;
  const match = FIND.exec(text);
  if (!match) return;
  const icon = document.createElement('span');
  icon.className = 'px-wrap';
  icon.setAttribute('role', 'img');
  icon.setAttribute('aria-label', match[1]);
  icon.innerHTML = SVGS[match[1]];
  const rest = node.splitText(match.index);
  rest.nodeValue = rest.nodeValue.slice(match[0].length);
  rest.before(icon);
  swapText(rest);
}

function swapIn(root) {
  if (root.nodeType === Node.TEXT_NODE) return swapText(root);
  if (root.nodeType !== Node.ELEMENT_NODE || root.closest('script, style, textarea, title, svg')) return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const texts = [];
  while (walker.nextNode()) texts.push(walker.currentNode);
  texts.forEach(swapText);
}

export function initPixelIcons() {
  swapIn(document.body);
  new MutationObserver((changes) => {
    for (const change of changes) {
      if (change.type === 'characterData') swapText(change.target);
      else change.addedNodes.forEach(swapIn);
    }
  }).observe(document.body, { childList: true, subtree: true, characterData: true });
}
